language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nikash19/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nikash19/react-test npm test -- --coverage

after_success:
  - docker build -t nikash19/multi-client ./client
  - docker build -t nikash19/multi-server ./server
  - docker build -t nikash19/multi-nginx ./nginx
  - docker build -t nikash19/multi-worker ./worker
  # Log into dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push nikash19/multi-client
  - docker push nikash19/multi-server
  - docker push nikash19/multi-worker
  - docker push nikash19/multi-nginx